FROM debian:bookworm-slim

WORKDIR /app

RUN useradd --system --no-create-home --uid 10001 appuser

COPY cmd/accrual/accrual_linux_amd64 /app/accrual
RUN chmod 0555 /app/accrual

USER appuser

EXPOSE 8080

ENTRYPOINT ["/app/accrual"]
