sonar.projectKey=xhrobj_gophermart
sonar.organization=xhrobj
sonar.sources=.
sonar.go.coverage.reportPaths=coverage.out

sonar.coverage.exclusions=\
  cmd/**,\
  internal/config/**,\
  internal/database/**,\
  internal/logger/**,\
  internal/migration/**,\
  internal/model/**,\
  **/*_test.go

sonar.cpd.exclusions=\
  **/*_test.go,\
  migrations/**
