name: (-_-) GO CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  go-ci:
    name: Quality checks -> lint, build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: (^_^) Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.11

      - name: (^_^) Build gophermart
        run: make build

      - name: (^_^) Run tests
        run: go test -race ./...
