name: (-_-) GO CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  go-ci:
    name: Quality checks -> lint, build and test
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.mod
          cache: true

      - name: (^_^) Run golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8
        with:
          version: v2.11

      - name: (^_^) Build gophermart
        run: make build

      - name: (^_^) Run tests with coverage
        run: make test-coverage

      - name: (^_^) Run race tests
        run: make test-race

      - name: (^_^) SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@299e4b793aaa83bf2aba7c9c14bedbb485688ec4 # v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
